#!/bin/sh

mv opsworks-custom-cookbooks/.git .git.tmp
mv opsworks-custom-cookbooks/unicorn .
bin/berks --path opsworks-custom-cookbooks
mv .git.tmp opsworks-custom-cookbooks/.git
mv unicorn opsworks-custom-cookbooks/
